name: goreleaser

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Run GoReleaser (snapshot for PRs, normal for tag)
        uses: goreleaser/goreleaser-action@v6
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            goreleaser release --snapshot --rm-dist
          else
            goreleaser release --rm-dist
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
